### ISSUE TITLE
Doesn't work for a very simple test

### ISSUE THREAD

**Issue by skrugly** [dpreussler/kotlin-testrunner#11]
```
@RunWith(KotlinTestRunner::class)
@OpenedClasses(FinalClass::class)
class FinalClassTest {
    @Test
    fun test() {
        val mock = Mockito.mock(FinalClass::class.java)
    }
}

class FinalClass {
    fun finalFun() { }
}
```

Got:

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class adambl4.FinalClass

Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#findClass

    at adambl4.FinalClassTest.test(FinalClassTest.kt:14)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#findClass
    at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Resolved.loadClass(ClassInjector.java:401)
    at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:210)
    at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:204)
    at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:119)
    at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4344)
    at org.mockito.internal.creation.bytebuddy.MockBytecodeGenerator.generateMockClass(MockBytecodeGenerator.java:60)
    at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.generate(CachingMockBytecodeGenerator.java:72)
    at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(CachingMockBytecodeGenerator.java:64)
    at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.get(CachingMockBytecodeGenerator.java:27)
    at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createProxyClass(ByteBuddyMockMaker.java:54)
    at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:27)
    at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:32)
    at org.mockito.internal.MockitoCore.mock(MockitoCore.java:55)
    at org.mockito.Mockito.mock(Mockito.java:1449)
    at org.mockito.Mockito.mock(Mockito.java:1362)
    ... 27 more
Caused by: javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  de/jodamob/kotlin/testrunner/NoMoreFinalsClassLoader): attempted  duplicate class definition for name: "adambl4/FinalClass"
    at javassist.ClassPool.toClass(ClassPool.java:1170)
    at javassist.ClassPool.toClass(ClassPool.java:1113)
    at javassist.CtClass.toClass(CtClass.java:1320)
    at de.jodamob.kotlin.testrunner.NoMoreFinalsClassLoader.process(NoMoreFinalsClassLoader.kt:37)
    at de.jodamob.kotlin.testrunner.NoMoreFinalsClassLoader.loadClass(NoMoreFinalsClassLoader.kt:24)
    at net.bytebuddy.dynamic.loading.MultipleParentClassLoader.loadClass(MultipleParentClassLoader.java:55)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Resolved.loadClass(ClassInjector.java:397)
    ... 41 more
Caused by: java.lang.LinkageError: loader (instance of  de/jodamob/kotlin/testrunner/NoMoreFinalsClassLoader): attempted  duplicate class definition for name: "adambl4/FinalClass"
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at javassist.ClassPool.toClass2(ClassPool.java:1183)
    at javassist.ClassPool.toClass(ClassPool.java:1164)
    ... 53 more


Process finished with exit code -1
```

Dependencies:

```
testCompile 'de.jodamob.kotlin:kotlin-runner-junit4:0.3.1'
testCompile "org.mockito:mockito-core:1.10.19"
```

**Comment by dpreussler** [comment]
@Adambl4 
this looks like https://github.com/dpreussler/kotlin-testrunner/issues/10

It seems you have another dependency using an earlier Mockito 2 version.
The stacktrace shows that Mockito 2.0 is used independent of your 1.10.19 import  (as 2.0 is based on byte buddy).

Try to find out which of your dependency used the 2.0.X version and try to exclude this and replace by something like:
testCompile 'org.mockito:mockito-core:2.0.82-beta'  
Newer version of 2.0 dont have this problem anymore.

The sample itself works fine on my side, nothing wrong there

**Comment by dpreussler** [comment]
@Adambl4 did you find it?
I think I had this through kotlin-mockito that has a reference to mockito2

testCompile ('com.nhaarman:mockito-kotlin:0.5.0') {
        exclude group: "org.mockito"
    }

**Comment by skrugly** [comment]
Yeah, it works with Mockito `2.0.82-beta`

**Comment by carloxavier** [comment]
hi! I'm getting this exception while also making sure I'm on a fairly new version of mockito (i.e. 2.15.0 as of now). EDIT: mockito-core 2.4.3 was the last version I could verify working together with the kotlinTestRunner.

@dpreussler is the kotlinTestRunner still being maintained? 

I want to give it a try, even though there's support for this on mockito2, because mock-maker-inline is. producing some very slow test suites for us
